version: '3'

services:
  app:
    build:
      context: ./
    restart: always
    ports:
      - 4000:4000

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    volumes:
      - ./database/db-definition.sql:/docker-entrypoint-initdb.d/db-definition.sql
      - ./database/db-definition.sql:/database/db-definition.sql
      - ./database/db-definition:/database/db-definition/
      - ./database/postgresql.conf:/etc/postgresql.conf

  server:
    build:
      context: ./server
    ports:
      - 19830:3000

  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080
