version: '3'

services:
  app:
    build:
      context: ./wudlet-app
    restart: always
    ports:
      - 4000:4000
    volumes:
      - appvolume:/app/build/ # build files will be added at this directory !!!

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: user123
      POSTGRES_DB: db123
    volumes:
      - ./database/db-definition.sql:/docker-entrypoint-initdb.d/db-definition.sql
      - ./database/db-definition.sql:/database/db-definition.sql
      - ./database/db-definition:/database/db-definition/
      - ./database/postgresql.conf:/etc/postgresql.conf

  nginx:
    build:
      context: ./nginx
    ports:
      - '80:80'
    volumes:
      - appvolume:/usr/share/nginx/html/app # Copy React App's build files to the Nginx directory

  server:
    build:
      context: ./server
    ports:
      - 19830:3000

volumes:
  appvolume:
